### ISSUE TITLE
Layer count mismatch

### ISSUE THREAD

**Issue by QUEST2179** [lewis-chinery/Humatch#1]
tried the example in notebook folder

(20, 3)
   is_human                                              heavy                                              light
0         1  QVQ-LVQSGA-EVNKPGASVKVSCKASGYTF---------TGYVVH...  EIV-LTQSPVTLSLSPGERATLSCRASQSV-----------SFYLA...
1         1  QVQ-LVQSGA-EVKKPGASVKVSCKASGYTF---------TGYYMH...  SYE-LTQPPS-VSVSPGQTARITCSGDALP-----------KQYAY...
Traceback (most recent call last):
  File "C:\Users\work\antibody\Humatch-master\testClassify.py", line 25, in <module>
    cnn_heavy = load_cnn(os.path.join(weights_dir, "heavy.weights.h5"), "heavy")
  File "C:\Users\work\antibody\Humatch-master\Humatch\model.py", line 130, in load_cnn
    CNN.load_weights(weights)
  File "C:\Users\miniconda3\envs\gpu9\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\miniconda3\envs\gpu9\lib\site-packages\keras\saving\hdf5_format.py", line 817, in load_weights_from_hdf5_group
    raise ValueError(
ValueError: Layer count mismatch when loading weights from file. Model expected 3 layers, found 0 saved layers.

**Comment by lewis-chinery** [comment]
Hi, I just tried deleting everything, reinstalling, and running the notebooks and it seemed to work OK for me (the weights download automatically). Could you please provide a bit more information:

- Which notebook did you try to run?
- Which cell did the notebook fail at?
- How did you set up your environment? (It looks like you're perhaps using conda and not venv)
- How are you running your notebook? (I am using VSCode and running on Linux Fedora 38)
- Did you create the testClassify.py file and what does this look like? (It seems like this is being called too)

If you do need to use a different set-up to that described in the README (especially using conda and not venv) then you could try manually downloading the weights as described in the README and trying again

**Comment by jesperdlau** [comment]
I had the same error and fixed it by upgrading Tensorflow to 2.17. Then I got a different error, something like:
`TypeError: generator yielded an element that did not match the expected structure. The expected structure was (tf.float64,), but the yielded element was [[[-0.47  0.24  0.07 ...`

This I fixed by changing the way the data generator is used inside the classify script, for the predict_from_list_of_seq_strs function.
Instead of 
`return model.predict(test_generator, verbose=CNN_verbose)`
I used:
`return model.predict(next(iter(test_generator)), batch_size=batch_size, verbose=CNN_verbose)`
(Remember to "pip install ." after changing code)
I other words, I parse the data itself, not the generator. I seems like the custom generator isn't compatible with Tensorflow 2.17 at least. Hope it makes sense. So far it works, but might not be the case always. It took me a long time to figure out. 

@lewis-chinery Can you please share the exact package versions you have?

**Comment by lewis-chinery** [comment]
Hi, apologies for the big delay in replying to this (I've been away) and thank you for flagging the issue!

For now, I have held off on making the code change you mentioned in case this causes issues with other versions. Instead, I've added minimum package version numbers to the setup.py and I have listed my full setup below for comparison. (Funnily, I do seem to use TF 2.17!)

Please let me know if you try this with the new versions. If it still doesn't work, could you please share more details of your environment and OS?

Thanks!

```
pip list

Package                      Version
---------------------------- -----------
absl-py                      2.1.0
anarci                       1.3
asttokens                    2.4.1
astunparse                   1.6.3
biopython                    1.84
certifi                      2024.8.30
charset-normalizer           3.3.2
comm                         0.2.2
contourpy                    1.3.0
cycler                       0.12.1
debugpy                      1.8.6
decorator                    5.1.1
exceptiongroup               1.2.2
executing                    2.1.0
flatbuffers                  24.3.25
fonttools                    4.54.1
gast                         0.6.0
google-pasta                 0.2.0
grpcio                       1.66.2
h5py                         3.12.1
hmmer                        3.4.0.0
Humatch                      1.0.0
idna                         3.10
importlib_metadata           8.5.0
importlib_resources          6.4.5
ipykernel                    6.29.5
ipython                      8.18.1
jedi                         0.19.1
joblib                       1.4.2
jupyter_client               8.6.3
jupyter_core                 5.7.2
keras                        3.5.0
kiwisolver                   1.4.7
libclang                     18.1.1
llvmlite                     0.43.0
Markdown                     3.7
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.9.2
matplotlib-inline            0.1.7
mdurl                        0.1.2
ml-dtypes                    0.4.1
namex                        0.0.8
nest-asyncio                 1.6.0
numba                        0.60.0
numpy                        1.26.4
opt_einsum                   3.4.0
optree                       0.12.1
packaging                    24.1
pandas                       2.2.3
parso                        0.8.4
pexpect                      4.9.0
pillow                       10.4.0
pip                          22.3.1
platformdirs                 4.3.6
prompt_toolkit               3.0.48
protobuf                     4.25.5
psutil                       6.0.0
ptyprocess                   0.7.0
pure_eval                    0.2.3
Pygments                     2.18.0
pyparsing                    3.1.4
python-dateutil              2.9.0.post0
pytz                         2024.2
PyYAML                       6.0.2
pyzmq                        26.2.0
requests                     2.32.3
rich                         13.8.1
scikit-learn                 1.5.2
scipy                        1.13.1
seaborn                      0.13.2
setuptools                   65.5.1
six                          1.16.0
sparse                       0.15.4
stack-data                   0.6.3
tensorboard                  2.17.1
tensorboard-data-server      0.7.2
tensorflow                   2.17.0
tensorflow-io-gcs-filesystem 0.37.1
termcolor                    2.4.0
threadpoolctl                3.5.0
tornado                      6.4.1
tqdm                         4.66.5
traitlets                    5.14.3
typing_extensions            4.12.2
tzdata                       2024.2
urllib3                      2.2.3
wcwidth                      0.2.13
Werkzeug                     3.0.4
wheel                        0.44.0
wrapt                        1.16.0
zipp                         3.20.2
```

**Comment by lewis-chinery** [comment]
Closing after fix suggested in issue `TypeError: generator yielded an element that did not match the expected structure. #3` solved the above.
