### ISSUE TITLE
TypeError: `generator` yielded an element that did not match the expected structure. 

### ISSUE THREAD

**Issue by XWcode11** [lewis-chinery/Humatch#3]
## errors:
(humatch) [test@localhost Humatch]$ Humatch-classify -H QVQLVQSGAEVNKPGASVKVSCKASGYTFTGYVVHWVRQAPGQRLEWMGWINTGNGDTKYSQKFQGRVSITRDTSANTAYMEVSTLRSEDTAVYYCARDRGGSGDFDYWGQGTLVTVSS -L EIVLTQSPVTLSLSPGERATLSCRASQSVSFYLAWYQQKPGQAPRLLICDASNRATGIPARFSGSGSGTDFTLTISSLEPEDFAVYYCQQRSDWPYTFGQGTKLEIK -s
Traceback (most recent call last):
  File "/home/kl/anaconda3/envs/humatch/bin/Humatch-classify", line 8, in <module>
    sys.exit(command_line_interface())
  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/Humatch/classify.py", line 158, in command_line_interface
    predictions_heavy = predict_from_list_of_seq_strs(H_seqs, load_cnn(HEAVY_WEIGHTS, "heavy"))
  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/Humatch/classify.py", line 33, in predict_from_list_of_seq_strs
    return model.predict(test_generator, verbose=CNN_verbose)
  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 5983, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_1_device_/job:localhost/replica:0/task:0/device:CPU:0}} TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float64,), but the yielded element was [[[-0.47  0.24  0.07 ... -0.71 -0.03 -2.33]
  [-0.74 -0.71  2.04 ...  0.06 -0.46  0.65]
  [-0.47  0.24  0.07 ... -0.71 -0.03 -2.33]
  ...
  [-0.74 -0.71  2.04 ...  0.06 -0.46  0.65]
  [ 0.81 -1.08  0.16 ... -1.15 -0.97 -0.23]
  [ 0.81 -1.08  0.16 ... -1.15 -0.97 -0.23]]].
Traceback (most recent call last):

  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 204, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/tensorflow/python/data/util/nest.py", line 237, in flatten_up_to
    return nest_util.flatten_up_to(

  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/tensorflow/python/util/nest_util.py", line 1541, in flatten_up_to
    return _tf_data_flatten_up_to(shallow_tree, input_tree)

  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/tensorflow/python/util/nest_util.py", line 1570, in _tf_data_flatten_up_to
    _tf_data_assert_shallow_structure(shallow_tree, input_tree)

  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/tensorflow/python/util/nest_util.py", line 1414, in _tf_data_assert_shallow_structure
    raise TypeError(

TypeError: If shallow structure is a sequence, input must also be a sequence. Input has type: 'ndarray'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)

  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 643, in wrapper
    return func(*args, **kwargs)

  File "/home/kl/anaconda3/envs/humatch/lib/python3.9/site-packages/tensorflow/python/data/ops/from_generator_op.py", line 206, in generator_py_func
    raise TypeError(

TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float64,), but the yielded element was [[[-0.47  0.24  0.07 ... -0.71 -0.03 -2.33]
  [-0.74 -0.71  2.04 ...  0.06 -0.46  0.65]
  [-0.47  0.24  0.07 ... -0.71 -0.03 -2.33]
  ...
  [-0.74 -0.71  2.04 ...  0.06 -0.46  0.65]
  [ 0.81 -1.08  0.16 ... -1.15 -0.97 -0.23]
  [ 0.81 -1.08  0.16 ... -1.15 -0.97 -0.23]]].

	 [[{{node PyFunc}}]] [Op:IteratorGetNext] name: 

## packages version
 flatbuffers-24.3.25 keras-3.6.0 ml-dtypes-0.3.2 tensorboard-2.16.2 tensorflow-2.16.1

thanks!

**Comment by XWcode11** [comment]
I modified the CustomDataGenerator class in dataset.py, and the issue has been resolved.
```

class CustomDataGenerator(tf.keras.utils.Sequence):
    '''
    Custom generator is required for sparse data input to keras model
    tf.keras.utils.Sequence allows multiprocessing in safe way (won't train on same batch twice)

    :param seqs: list of aligned sequence strings
    :param batch_size: int, batch size for training
    :param num_cpus: int, number of cpus to use when encoding sequences
    '''
    def __init__(self, seqs, batch_size=16384, num_cpus=None):
        '''
        '''
        super().__init__()
        self.seqs = seqs
        self.batch_size = batch_size
        self.num_cpus = num_cpus

    def __len__(self):
        '''
        Get the number of batches
        '''
        return math.ceil(len(self.seqs) / self.batch_size)

    def __getitem__(self, index):
        '''
        Get Kidera encoded ndarrays, X, for a batch of sequences
        '''
        low_idx = index * self.batch_size
        high_idx = min((index + 1) * self.batch_size, len(self.seqs))
        batch_seqs = self.seqs[low_idx:high_idx]
        
        # modified
        X = get_X_from_list_of_seq_strs(batch_seqs, self.num_cpus)
        
        if X.dtype != np.float64:
            X = X.astype(np.float64)
        
        return (X,)
        
```

**Comment by lewis-chinery** [comment]
Hi, thank you very much for finding and fixing this issue! (Sorry for the very late reply, I have been away.)

I have held off on changing the dataset code for the moment (though I believe this should be OK to merge if needed in the future) as I am interested to know if the most recent commit with specified package versions fixes your issue too.

Please let me know if you try this and do provide more details on your environment and OS if you continue to face the same problem. I have provided a full list of my package versions below for comparison.

Thanks!

```
pip list

Package                      Version
---------------------------- -----------
absl-py                      2.1.0
anarci                       1.3
asttokens                    2.4.1
astunparse                   1.6.3
biopython                    1.84
certifi                      2024.8.30
charset-normalizer           3.3.2
comm                         0.2.2
contourpy                    1.3.0
cycler                       0.12.1
debugpy                      1.8.6
decorator                    5.1.1
exceptiongroup               1.2.2
executing                    2.1.0
flatbuffers                  24.3.25
fonttools                    4.54.1
gast                         0.6.0
google-pasta                 0.2.0
grpcio                       1.66.2
h5py                         3.12.1
hmmer                        3.4.0.0
Humatch                      1.0.0
idna                         3.10
importlib_metadata           8.5.0
importlib_resources          6.4.5
ipykernel                    6.29.5
ipython                      8.18.1
jedi                         0.19.1
joblib                       1.4.2
jupyter_client               8.6.3
jupyter_core                 5.7.2
keras                        3.5.0
kiwisolver                   1.4.7
libclang                     18.1.1
llvmlite                     0.43.0
Markdown                     3.7
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
matplotlib                   3.9.2
matplotlib-inline            0.1.7
mdurl                        0.1.2
ml-dtypes                    0.4.1
namex                        0.0.8
nest-asyncio                 1.6.0
numba                        0.60.0
numpy                        1.26.4
opt_einsum                   3.4.0
optree                       0.12.1
packaging                    24.1
pandas                       2.2.3
parso                        0.8.4
pexpect                      4.9.0
pillow                       10.4.0
pip                          22.3.1
platformdirs                 4.3.6
prompt_toolkit               3.0.48
protobuf                     4.25.5
psutil                       6.0.0
ptyprocess                   0.7.0
pure_eval                    0.2.3
Pygments                     2.18.0
pyparsing                    3.1.4
python-dateutil              2.9.0.post0
pytz                         2024.2
PyYAML                       6.0.2
pyzmq                        26.2.0
requests                     2.32.3
rich                         13.8.1
scikit-learn                 1.5.2
scipy                        1.13.1
seaborn                      0.13.2
setuptools                   65.5.1
six                          1.16.0
sparse                       0.15.4
stack-data                   0.6.3
tensorboard                  2.17.1
tensorboard-data-server      0.7.2
tensorflow                   2.17.0
tensorflow-io-gcs-filesystem 0.37.1
termcolor                    2.4.0
threadpoolctl                3.5.0
tornado                      6.4.1
tqdm                         4.66.5
traitlets                    5.14.3
typing_extensions            4.12.2
tzdata                       2024.2
urllib3                      2.2.3
wcwidth                      0.2.13
Werkzeug                     3.0.4
wheel                        0.44.0
wrapt                        1.16.0
zipp                         3.20.2
```

**Comment by QUEST2179** [comment]
I confirmed this program runs successfully after modifying dataset.py as suggested by [XWcode11] and using tensorflow 2.17.0

My question is: how to modify the code to humanize nanobody or only heavy chain?

**Comment by lewis-chinery** [comment]
Thank you for confirming the above fix works! I will merge the pull request now.

We allow single-chain (heavy or light) _classification_ of antibody chains as we appreciate much sequence data is unpaired. However, we encourage users to _humanise_ both antibody chains together as we believe this is important to maintain the stability of the Fv and avoid immunogenic epitopes forming between the chains.

We don't recommend this, but if you _really_ wanted to humanise just the heavy antibody chain then you could include a dummy light chain and then set `GL_target_score_L`, `CNN_target_score_L`, and `CNN_target_score_P` to be zero in your config file e.g. `Humatch/configs/default.yaml`. For speed reasons, you may also wish to include all `CANONICAL_NUMBERING` positions from `Humatch/utils.py` in `CNN_fixed_imgt_positions_L` in your custom config file.

Humatch has not been designed to handle nanobody sequences for classification or humanisation. As Humatch has been trained only on antibody sequences, it will not understand that previously hidden interface residues may cause immunogenic reactions.

I hope this helps. I will close this issue now as the topic is changing, but do raise another issue or send me a message if you have any other Qs!
